repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        exclude: yarn.lock
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        files: \.sh
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: eslint-prettier
        name: Lint and Style
        language: system
        files: \.(j|t)sx?$
        entry: bash -c 'yarn format && yarn lint'
        pass_filenames: false
exclude: 'examples/*'
